import "./globals.css";
import { Inter } from "next/font/google";
import { Header } from "./(components)/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* <AuthProvider
        authType="cookie"
        authName="_auth"
        cookieDomain={window.location.hostname}
        cookieSecure={false}
      >
        <BrowserRouter> */}
      <html lang="en">
        <head></head>
        <body className={inter.className}>
          <Header></Header>
          {children}
        </body>
      </html>
      {/* </BrowserRouter>
      </AuthProvider> */}
    </>
  );
}
